# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
theme:            minima

# Setup
title:            'Renee Wu'
tagline:          'A blog'
description:      'A place where Renee puts her thoughts to'
url:              https://wurenee.github.io
baseurl:          /

author:
  name:           'Renee Wu'
  url:            

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/wurenee
